apiVersion: 1
prune: true

datasources:
  - name: $GRAFANA_DS_NAME
    uid: awdw2022
    type: mssql
    access: proxy
    url: $GRAFANA_DS_HOST
    user: $GRAFANA_DS_USER
    isDefault: true
    editable: true
    jsonData:
      database: $GRAFANA_DS_DB
      encrypt: "false"
      maxOpenConns: 25
      maxIdleConns: 25
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      connectionTimeout: 0
    secureJsonData:
      password: $GRAFANA_DS_PASSWORD