{
 "title": "Ventas General",
 "time": { "from": "2010-01-01T00:00:00.000Z", "to": "2014-01-01T00:00:00.000Z" },
 "panels": [
  {
   "title": "Territorios",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "AdventureWorksDW2022",
     "rawSql": "SELECT\r\n    CASE Pais\r\n        WHEN 'United States'  THEN 'USA'\r\n        WHEN 'Australia'      THEN 'AUS'\r\n        WHEN 'United Kingdom' THEN 'GBR'\r\n        WHEN 'Germany'        THEN 'DEU'\r\n        WHEN 'France'         THEN 'FRA'\r\n        WHEN 'Canada'         THEN 'CAN'\r\n        ELSE NULL\r\n    END AS lookup,\r\n    GrupoTerritorial,\r\n    Pais,\r\n    TotalVentas\r\nFROM dbo.vw_BI_VentasPorTerritorioGrupo\r\nWHERE CASE Pais\r\n        WHEN 'United States'  THEN 'USA'\r\n        WHEN 'Australia'      THEN 'AUS'\r\n        WHEN 'United Kingdom' THEN 'GBR'\r\n        WHEN 'Germany'        THEN 'DEU'\r\n        WHEN 'France'         THEN 'FRA'\r\n        WHEN 'Canada'         THEN 'CAN'\r\n        ELSE NULL\r\n      END IS NOT NULL\r\nORDER BY TotalVentas DESC;"
    }
   ]
  },
  {
   "title": "Productos",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "AdventureWorksDW2022",
     "rawSql": "SELECT\r\n  Categoria,\r\n  Subcategoria,\r\n  TotalVentas\r\nFROM dbo.vw_BI_VentasPorSubcategoria\r\nORDER BY TotalVentas DESC;"
    },
    {
     "dataset": "AdventureWorksDW2022",
     "rawSql": "SELECT TOP 10\r\n  Producto,\r\n  TotalVentas,\r\n  UtilidadBruta\r\nFROM dbo.vw_BI_TopProductos\r\nORDER BY TotalVentas DESC;"
    }
   ]
  },
  {
   "title": "Tendencia Mensual",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "AdventureWorksDW2022",
     "rawSql": "SELECT\r\n  FechaMes,\r\n  TotalVentas,\r\n  CantidadVendida,\r\n  TotalOrdenes,\r\n  TicketPromedio\r\nFROM dbo.vw_BI_VentasPorMes\r\nORDER BY FechaMes;"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "AdventureWorksDW2022",
     "rawSql": "SELECT\r\n  Pais,\r\n  TotalVentas\r\nFROM dbo.vw_BI_VentasPorPais\r\nORDER BY TotalVentas DESC"
    }
   ]
  },
  {
   "title": "Ventas por año ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "AdventureWorksDW2022",
     "rawSql": "SELECT \r\n  CAST(CONCAT(CalendarYear, '-01-01') AS DATE) AS Fecha,\r\n  TotalVentas\r\nFROM dbo.vw_BI_VentasPorAnio\r\nORDER BY Fecha;\r\n"
    }
   ]
  },
  {
   "title": "Ventas por categoría",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "AdventureWorksDW2022",
     "rawSql": "SELECT\r\n  Categoria,\r\n  TotalVentas\r\nFROM dbo.vw_BI_VentasPorCategoria\r\nORDER BY TotalVentas DESC"
    }
   ]
  }
 ]
}