trigger:
  branches:
    include:
      - main
  paths:
    include:
      - app/**
    exclude:
      - api/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'sc-azure-bi'
  imageRepository: 'bi-portal'
  containerRegistry: 'acrbistudentdev01.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/app/Dockerfile'
  tag: '$(Build.BuildId)'
  imageTag: '$(containerRegistry)/$(imageRepository):$(tag)'

stages:
  - stage: Build
    displayName: Build and Push Image
    jobs:
      - job: BuildAndPush
        displayName: Build Docker Image
        steps:
          - task: Docker@2
            displayName: Build and Push Image
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)

        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureContainerApps@1
                  displayName: Deploy bi-portal
                  inputs:
                    azureSubscription: 'sc-azure-bi'
                    containerAppName: 'bi-portal'
                    resourceGroup: 'rg-bi-student-dev'
                    imageToDeploy: $(imageTag)
                    ingress: 'external'
                    targetPort: 80
